# Generated by Django 3.2.7 on 2021-10-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='settings_name',
            new_name='setting_name',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='settings_value',
            new_name='setting_value',
        ),
    ]
