# Generated by Django 3.2.7 on 2021-10-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20210928_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apis',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='apitest',
            old_name='Product',
            new_name='product',
        ),
    ]
