# Generated by Django 3.2.7 on 2021-10-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20211010_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='api_method',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='api_param_value',
            field=models.CharField(max_length=800, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='api_response',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='api_result',
            field=models.CharField(max_length=800, verbose_name='预期结果'),
        ),
    ]
