# Generated by Django 3.2.7 on 2021-10-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_case_name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('app_case_result', models.BooleanField(verbose_name='测试结果')),
                ('app_case_tester', models.CharField(max_length=16, verbose_name='测试负责人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'app测试用例',
                'verbose_name_plural': 'app测试用例',
            },
        ),
        migrations.CreateModel(
            name='AppCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_case_step', models.CharField(max_length=200, verbose_name='测试步骤')),
                ('app_case_object_name', models.CharField(max_length=200, verbose_name='测试对象名称描述')),
                ('app_case_find_method', models.CharField(max_length=200, verbose_name='定位方式')),
                ('app_case_element', models.CharField(max_length=200, verbose_name='控件元素')),
                ('app_case_op_method', models.CharField(max_length=200, verbose_name='操作方法')),
                ('app_case_test_data', models.CharField(max_length=200, null=True, verbose_name='测试数据')),
                ('app_case_assert_data', models.CharField(max_length=200, verbose_name='验证数据')),
                ('app_case_result', models.BooleanField(verbose_name='测试结果')),
                ('creat_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('app_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test.appcase')),
            ],
        ),
    ]
