# Generated by Django 3.2.7 on 2021-10-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcasestep',
            name='app_case_test_data',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='测试数据'),
        ),
    ]
