# Generated by Django 3.2.7 on 2021-10-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugAdmin',
        ),
    ]
